# Generated by Django 5.0.3 on 2024-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20, verbose_name='cep')),
                ('logradouro', models.CharField(blank=True, max_length=35, null=True, verbose_name='rua')),
                ('complemento', models.CharField(blank=True, max_length=20, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=20, null=True, verbose_name='bairro')),
                ('localidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='localidade')),
                ('uf', models.CharField(blank=True, max_length=20, null=True, verbose_name='uf')),
            ],
        ),
    ]
